logging:
  # місце розміщення папки для логів
  directory: output/logs

  # рівень логування
  level: DEBUG

  # назви файлів для логів
  files:
    # Назва файлу для логів додатку
    application_log: "app.log"
    
    # Назва файлу для логів помилок
    error_log: "error.log"
